import { Market, Crop, StateDistrictHierarchy } from '../types';

export interface MarketPriceRecord {
  marketId: string;
  marketName: string;
  cropId: string;
  cropName: string;
  minPrice: number;
  maxPrice: number;
  modalPrice: number;
  unit: string;
  arrivalQuantityQtl: number;
  lastUpdated: string;
  dataStatus: 'VERIFIED' | 'SAMPLE_DEMO' | 'OFFICIAL' | 'COMMUNITY_SUBMITTED';
}

// 1. All 36 States & Union Territories of India
export const ALL_INDIA_STATES: string[] = [
  'West Bengal',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

// 2. Comprehensive District & Locality Hierarchy with All 23 West Bengal Districts
export const STATE_DISTRICT_HIERARCHY: Record<string, { district: string; localities: string[] }[]> = {
  'West Bengal': [
    {
      district: 'Kolkata',
      localities: [
        'Sealdah',
        'Mechua',
        'Posta / Burrabazar',
        'Maniktala',
        'Kankurgachi',
        'Gariahat',
        'Lake Market',
        'Bagbazar',
        'Jadavpur',
        'Behala',
      ],
    },
    {
      district: 'Howrah',
      localities: ['Howrah Wholesale Yard', 'Ramrajatala', 'Kadamtala', 'Shibpur', 'Uluberia'],
    },
    {
      district: 'Hooghly',
      localities: ['Bally', 'Belur', 'Serampore', 'Singur', 'Chinsurah', 'Tarakeswar'],
    },
    {
      district: 'North 24 Parganas',
      localities: ['Barasat', 'Basirhat', 'Bangaon', 'Habra', 'Barrackpore'],
    },
    {
      district: 'South 24 Parganas',
      localities: ['Baruipur', 'Canning', 'Diamond Harbour', 'Kakdwip', 'Sonarpur'],
    },
    {
      district: 'Nadia',
      localities: ['Krishnanagar', 'Ranaghat', 'Tehatta', 'Kalyani', 'Bethuadahari'],
    },
    {
      district: 'Murshidabad',
      localities: ['Berhampore', 'Kandi', 'Jangipur', 'Lalbagh', 'Dhuliyan'],
    },
    {
      district: 'Purba Bardhaman',
      localities: ['Bardhaman Sadar', 'Memari', 'Kalna', 'Katwa', 'Raina'],
    },
    {
      district: 'Paschim Bardhaman',
      localities: ['Asansol', 'Durgapur', 'Raniganj'],
    },
    {
      district: 'Bankura',
      localities: ['Bankura Town', 'Bishnupur', 'Khatra', 'Kotulpur'],
    },
    {
      district: 'Purulia',
      localities: ['Purulia Sadar', 'Raghunathpur', 'Jhalda', 'Manbazar'],
    },
    {
      district: 'Birbhum',
      localities: ['Suri', 'Bolpur (Santiniketan)', 'Rampurhat', 'Sainthia'],
    },
    {
      district: 'Paschim Medinipur',
      localities: ['Midnapore Sadar', 'Kharagpur', 'Ghatal', 'Garhbeta'],
    },
    {
      district: 'Purba Medinipur',
      localities: ['Tamluk', 'Haldia', 'Contai', 'Egra', 'Kolaghat'],
    },
    {
      district: 'Jhargram',
      localities: ['Jhargram Town', 'Gopiballavpur', 'Belpahari'],
    },
    {
      district: 'Malda',
      localities: ['English Bazar', 'Old Malda', 'Chanchal', 'Samsi'],
    },
    {
      district: 'Uttar Dinajpur',
      localities: ['Raiganj', 'Islampur', 'Dalkhola'],
    },
    {
      district: 'Dakshin Dinajpur',
      localities: ['Balurghat', 'Gangarampur', 'Buniadpur'],
    },
    {
      district: 'Jalpaiguri',
      localities: ['Jalpaiguri Sadar', 'Dhupguri', 'Malbazar'],
    },
    {
      district: 'Alipurduar',
      localities: ['Alipurduar Town', 'Falakata', 'Jaigaon'],
    },
    {
      district: 'Cooch Behar',
      localities: ['Cooch Behar Sadar', 'Dinhata', 'Mathabhanga', 'Tufanganj'],
    },
    {
      district: 'Darjeeling',
      localities: ['Siliguri Regulated Market', 'Darjeeling Town', 'Kurseong'],
    },
    {
      district: 'Kalimpong',
      localities: ['Kalimpong Town', 'Pedong', 'Gorubathan'],
    },
  ],
  Delhi: [
    {
      district: 'North Delhi',
      localities: ['Azadpur', 'Narela', 'Model Town'],
    },
    {
      district: 'South Delhi',
      localities: ['Saket', 'Okhla', 'Mehrauli'],
    },
    {
      district: 'East Delhi',
      localities: ['Ghazipur', 'Preet Vihar', 'Mayur Vihar'],
    },
    {
      district: 'West Delhi',
      localities: ['Keshopur', 'Punjabi Bagh', 'Janakpuri'],
    },
  ],
  'Uttar Pradesh': [
    {
      district: 'Meerut',
      localities: ['Meerut City Bypass', 'Daurala', 'Mawana', 'Sardhana'],
    },
    {
      district: 'Agra',
      localities: ['Agra Mandi Yard', 'Fatehabad', 'Khandauli'],
    },
    {
      district: 'Lucknow',
      localities: ['Dubagga Mandi', 'Sitapur Road Mandi', 'Alambagh'],
    },
    {
      district: 'Varanasi',
      localities: ['Paharariya Mandi', 'Rajatalab', 'Ramnagar'],
    },
  ],
  Maharashtra: [
    {
      district: 'Nashik',
      localities: ['Lasalgaon', 'Pimpalgaon', 'Nashik Road'],
    },
    {
      district: 'Navi Mumbai',
      localities: ['Vashi Sector 19', 'Turbhe', 'Nerul'],
    },
    {
      district: 'Pune',
      localities: ['Gultekdi Market Yard', 'Hadapsar', 'Kharki'],
    },
  ],
  Punjab: [
    {
      district: 'Ludhiana',
      localities: ['Khanna Grain Terminal', 'Ludhiana APMC Yard', 'Jagraon'],
    },
    {
      district: 'Jalandhar',
      localities: ['Maqsudan Mandi', 'Cantt Yard'],
    },
  ],
  Bihar: [
    {
      district: 'Patna',
      localities: ['Bazar Samiti Musallahpur', 'Danapur', 'Fatuha'],
    },
    {
      district: 'Purnia',
      localities: ['Gulabbagh Grain Mandi', 'Kasba', 'Banmankhi'],
    },
  ],
  Karnataka: [
    {
      district: 'Kolar',
      localities: ['Kolar APMC Tomato Yard', 'Malur', 'Bangarapet'],
    },
    {
      district: 'Bangalore Urban',
      localities: ['Yeshwanthpur Sub-Yard', 'KR Market', 'Binny Mills'],
    },
  ],
  'Tamil Nadu': [
    {
      district: 'Chennai',
      localities: ['Koyambedu Wholesale Complex', 'Madhavaram', 'Pallavaram'],
    },
    {
      district: 'Madurai',
      localities: ['Mattuthavani Central Market', 'Simmakkal'],
    },
  ],
  Gujarat: [
    {
      district: 'Mehsana',
      localities: ['Unjha Spices APMC', 'Kadi'],
    },
    {
      district: 'Rajkot',
      localities: ['Bedi Marketing Yard', 'Gondal APMC'],
    },
  ],
  'Madhya Pradesh': [
    {
      district: 'Indore',
      localities: ['Choithram Mandi Yard', 'Laxmi Bai Nagar Mandi'],
    },
    {
      district: 'Neemuch',
      localities: ['Neemuch APMC Terminal', 'Manasa'],
    },
  ],
  Assam: [
    {
      district: 'Kamrup Metropolitan',
      localities: ['Fancy Bazar Wholesale', 'Pamohi Fruit Market', 'Beltola'],
    },
  ],
  Odisha: [
    {
      district: 'Khurda',
      localities: ['Bhubaneswar Unit 1 Haat', 'Jatni'],
    },
    {
      district: 'Cuttack',
      localities: ['Malgodown Wholesale', 'Chhatra Bazar'],
    },
  ],
};

// 3. Complete Expanded List of Realistic Agricultural Mandis / Markets
export const ALL_SEEDED_MARKETS: Market[] = [
  // --- KOLKATA MARKETS ---
  {
    id: 'mkt_kol_sealdah',
    name: 'Sealdah Koley Market',
    district: 'Kolkata',
    state: 'West Bengal',
    locality: 'Sealdah',
    type: 'wholesale',
    lat: 22.5697,
    lng: 88.3712,
    address: 'Koley Market Building, Beliaghata Road, Sealdah, Kolkata, West Bengal - 700014',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T06:00:00Z',
    availableCrops: [
      'crop_potato',
      'crop_onion',
      'crop_tomato',
      'crop_brinjal',
      'crop_cabbage',
      'crop_cauliflower',
      'crop_green_chilli',
      'crop_pointed_gourd',
      'crop_bitter_gourd',
      'crop_ridge_gourd',
      'crop_ginger',
      'crop_garlic',
    ],
    contactPerson: 'Koley Market Wholesale Committee',
    openingHours: '03:00 AM - 01:00 PM (Wholesale Auction)',
    modalPriceSummary: {
      crop_potato: 15.8,
      crop_onion: 26.5,
      crop_tomato: 22.0,
      crop_green_chilli: 42.0,
      crop_brinjal: 28.0,
      crop_cabbage: 18.0,
      crop_cauliflower: 32.0,
      crop_pointed_gourd: 38.0,
    },
  },
  {
    id: 'mkt_kol_mechua',
    name: 'Mechua Fruit & Produce Market',
    district: 'Kolkata',
    state: 'West Bengal',
    locality: 'Mechua',
    type: 'wholesale',
    lat: 22.5825,
    lng: 88.3582,
    address: 'Mechua Bazar, Chittaranjan Avenue, Burrabazar, Kolkata, West Bengal - 700007',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T05:30:00Z',
    availableCrops: ['crop_onion', 'crop_potato', 'crop_ginger', 'crop_garlic', 'crop_tomato'],
    contactPerson: 'Mechua Merchants Association',
    openingHours: '04:00 AM - 02:00 PM',
    modalPriceSummary: {
      crop_potato: 16.2,
      crop_onion: 25.8,
      crop_garlic: 135.0,
      crop_ginger: 78.0,
    },
  },
  {
    id: 'mkt_kol_posta',
    name: 'Bara Bazar / Posta Wholesale Yard',
    district: 'Kolkata',
    state: 'West Bengal',
    locality: 'Posta / Burrabazar',
    type: 'wholesale',
    lat: 22.588,
    lng: 88.355,
    address: 'Posta Bazar, Strand Road, Near Howrah Bridge, Kolkata, West Bengal - 700006',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T06:15:00Z',
    availableCrops: ['crop_rice', 'crop_wheat', 'crop_mustard', 'crop_onion', 'crop_garlic'],
    contactPerson: 'Posta Commodity Clearinghouse',
    openingHours: '07:00 AM - 06:00 PM',
    modalPriceSummary: {
      crop_rice: 23.5,
      crop_wheat: 25.2,
      crop_mustard: 54.0,
      crop_onion: 25.0,
    },
  },
  {
    id: 'mkt_kol_maniktala',
    name: 'Maniktala Central Bazar',
    district: 'Kolkata',
    state: 'West Bengal',
    locality: 'Maniktala',
    type: 'retail',
    lat: 22.5862,
    lng: 88.3745,
    address: 'Maniktala Main Road crossing, Kolkata - 700054',
    dataStatus: 'SAMPLE_DEMO',
    lastUpdated: '2026-09-25T07:00:00Z',
    availableCrops: ['crop_potato', 'crop_tomato', 'crop_brinjal', 'crop_green_chilli', 'crop_pointed_gourd'],
    openingHours: '06:00 AM - 01:30 PM & 05:00 PM - 09:30 PM',
    modalPriceSummary: {
      crop_potato: 18.0,
      crop_tomato: 28.0,
      crop_brinjal: 34.0,
      crop_pointed_gourd: 45.0,
    },
  },
  {
    id: 'mkt_kol_gariahata',
    name: 'Gariahat Wholesale & Retail Complex',
    district: 'Kolkata',
    state: 'West Bengal',
    locality: 'Gariahat',
    type: 'retail',
    lat: 22.518,
    lng: 88.365,
    address: 'Gariahat Crossing, South Kolkata, West Bengal - 700019',
    dataStatus: 'SAMPLE_DEMO',
    lastUpdated: '2026-09-25T07:30:00Z',
    availableCrops: ['crop_potato', 'crop_onion', 'crop_tomato', 'crop_cabbage', 'crop_cauliflower'],
    openingHours: '06:30 AM - 09:00 PM',
    modalPriceSummary: {
      crop_potato: 19.5,
      crop_onion: 30.0,
      crop_tomato: 32.0,
      crop_cauliflower: 38.0,
    },
  },

  // --- HOWRAH MARKETS ---
  {
    id: 'mkt_how_wholesale',
    name: 'Howrah Wholesale Vegetable Terminal',
    district: 'Howrah',
    state: 'West Bengal',
    locality: 'Howrah Wholesale Yard',
    type: 'apmc',
    lat: 22.591,
    lng: 88.334,
    address: 'Station Road Yard, Howrah, West Bengal - 711101',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T05:00:00Z',
    availableCrops: ['crop_potato', 'crop_onion', 'crop_cabbage', 'crop_pointed_gourd'],
    modalPriceSummary: { crop_potato: 15.2, crop_onion: 25.0, crop_pointed_gourd: 36.0 },
  },
  {
    id: 'mkt_how_ramrajatala',
    name: 'Ramrajatala Market',
    district: 'Howrah',
    state: 'West Bengal',
    locality: 'Ramrajatala',
    type: 'retail',
    lat: 22.578,
    lng: 88.305,
    address: 'Ramrajatala Bazaar, Howrah, West Bengal - 711104',
    dataStatus: 'SAMPLE_DEMO',
    lastUpdated: '2026-09-25T07:00:00Z',
    availableCrops: ['crop_potato', 'crop_tomato', 'crop_brinjal', 'crop_ridge_gourd'],
    modalPriceSummary: { crop_potato: 17.5, crop_tomato: 26.0 },
  },

  // --- HOOGHLY & BALLY EXAMPLES ---
  {
    id: 'mkt_hooghly_bally_belur',
    name: 'Belur Bazar',
    district: 'Hooghly',
    state: 'West Bengal',
    locality: 'Bally',
    type: 'retail',
    lat: 22.632,
    lng: 88.352,
    address: 'Belur Station Road, Bally Municipality, Hooghly, West Bengal - 711205',
    dataStatus: 'SAMPLE_DEMO',
    lastUpdated: '2026-09-25T06:45:00Z',
    availableCrops: ['crop_potato', 'crop_onion', 'crop_tomato', 'crop_green_chilli', 'crop_bitter_gourd'],
    openingHours: '06:00 AM - 01:00 PM',
    modalPriceSummary: {
      crop_potato: 17.0,
      crop_onion: 28.0,
      crop_tomato: 25.0,
      crop_green_chilli: 45.0,
    },
  },
  {
    id: 'mkt_hooghly_bally_market',
    name: 'Bally Market Yard',
    district: 'Hooghly',
    state: 'West Bengal',
    locality: 'Bally',
    type: 'mandi',
    lat: 22.648,
    lng: 88.343,
    address: 'GT Road Bally Bazar, Hooghly, West Bengal - 711201',
    dataStatus: 'SAMPLE_DEMO',
    lastUpdated: '2026-09-25T06:15:00Z',
    availableCrops: ['crop_potato', 'crop_cabbage', 'crop_cauliflower', 'crop_pumpkin'],
    openingHours: '05:30 AM - 01:00 PM',
    modalPriceSummary: {
      crop_potato: 16.5,
      crop_cabbage: 16.0,
      crop_cauliflower: 30.0,
    },
  },
  {
    id: 'mkt_hooghly_singur',
    name: 'Singur Krishak Bazar Regulated Market',
    district: 'Hooghly',
    state: 'West Bengal',
    locality: 'Singur',
    type: 'apmc',
    lat: 22.812,
    lng: 88.225,
    address: 'Near Singur Railway Station, Hooghly, West Bengal - 712409',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T05:45:00Z',
    availableCrops: ['crop_potato', 'crop_rice', 'crop_pointed_gourd', 'crop_mustard'],
    modalPriceSummary: {
      crop_potato: 14.8,
      crop_rice: 21.8,
      crop_pointed_gourd: 32.0,
    },
  },

  // --- OTHER WEST BENGAL DISTRICT MARKETS ---
  {
    id: 'mkt_burdwan',
    name: 'Burdwan Krishak Bazar Mandi',
    district: 'Purba Bardhaman',
    state: 'West Bengal',
    locality: 'Bardhaman Sadar',
    type: 'cooperative',
    lat: 23.2324,
    lng: 87.8615,
    address: 'Near Sadar Station, Burdwan, West Bengal - 713101',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T06:00:00Z',
    availableCrops: ['crop_rice', 'crop_potato', 'crop_mustard', 'crop_pointed_gourd'],
    modalPriceSummary: {
      crop_rice: 21.5,
      crop_potato: 14.5,
      crop_mustard: 51.5,
    },
  },
  {
    id: 'mkt_wb_siliguri',
    name: 'Siliguri Regulated Market (Darjeeling)',
    district: 'Darjeeling',
    state: 'West Bengal',
    locality: 'Siliguri Regulated Market',
    type: 'apmc',
    lat: 26.7271,
    lng: 88.3953,
    address: 'Mallaguri, Siliguri, Darjeeling, West Bengal - 734003',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T06:30:00Z',
    availableCrops: ['crop_ginger', 'crop_potato', 'crop_cabbage', 'crop_tomato'],
    modalPriceSummary: { crop_ginger: 68.0, crop_potato: 17.5, crop_tomato: 24.0 },
  },
  {
    id: 'mkt_wb_malda',
    name: 'Malda Samsi Agricultural Mandi',
    district: 'Malda',
    state: 'West Bengal',
    locality: 'Samsi',
    type: 'mandi',
    lat: 25.321,
    lng: 88.012,
    address: 'Samsi Station Yard, Malda, West Bengal - 732139',
    dataStatus: 'SAMPLE_DEMO',
    lastUpdated: '2026-09-25T05:00:00Z',
    availableCrops: ['crop_rice', 'crop_wheat', 'crop_mustard'],
    modalPriceSummary: { crop_rice: 21.0, crop_wheat: 24.0 },
  },
  {
    id: 'mkt_wb_midnapore',
    name: 'Midnapore Garhbeta Krishak Market',
    district: 'Paschim Medinipur',
    state: 'West Bengal',
    locality: 'Garhbeta',
    type: 'apmc',
    lat: 22.86,
    lng: 87.35,
    address: 'Garhbeta Block Yard, Paschim Medinipur, West Bengal - 721127',
    dataStatus: 'SAMPLE_DEMO',
    lastUpdated: '2026-09-25T05:30:00Z',
    availableCrops: ['crop_potato', 'crop_rice', 'crop_pointed_gourd'],
    modalPriceSummary: { crop_potato: 14.2, crop_rice: 21.2 },
  },

  // --- ALL INDIA NATIONAL CLEARINGHOUSE MANDIS ---
  {
    id: 'mkt_azadpur',
    name: 'Azadpur Mandi (APMC)',
    district: 'North Delhi',
    state: 'Delhi',
    locality: 'Azadpur',
    type: 'apmc',
    lat: 28.7153,
    lng: 77.1784,
    address: 'APMC Market Yard, GT Karnal Road, Azadpur, Delhi - 110033',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T06:00:00Z',
    availableCrops: ['crop_onion', 'crop_potato', 'crop_tomato', 'crop_wheat', 'crop_garlic'],
    modalPriceSummary: { crop_onion: 26.0, crop_potato: 16.5, crop_tomato: 24.0, crop_wheat: 24.8 },
  },
  {
    id: 'mkt_del_okhla',
    name: 'Okhla Vegetable & Fruit Mandi',
    district: 'South Delhi',
    state: 'Delhi',
    locality: 'Okhla',
    type: 'wholesale',
    lat: 28.5355,
    lng: 77.2798,
    address: 'Maa Anandmayee Marg, Okhla Phase 2, New Delhi - 110020',
    dataStatus: 'SAMPLE_DEMO',
    lastUpdated: '2026-09-25T06:30:00Z',
    availableCrops: ['crop_tomato', 'crop_brinjal', 'crop_cauliflower', 'crop_green_chilli'],
    modalPriceSummary: { crop_tomato: 25.0, crop_brinjal: 26.0 },
  },
  {
    id: 'mkt_aadhya',
    name: 'Aadhya Rural Aggregation Center',
    district: 'Meerut',
    state: 'Uttar Pradesh',
    locality: 'Meerut City Bypass',
    type: 'farmer_market',
    lat: 28.9845,
    lng: 77.7064,
    address: 'Sector 4 Bypass, Near Kisan Bhawan, Meerut, UP - 250001',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T07:15:00Z',
    availableCrops: ['crop_wheat', 'crop_mustard', 'crop_potato'],
    modalPriceSummary: { crop_wheat: 24.5, crop_mustard: 52.0, crop_potato: 15.0 },
  },
  {
    id: 'mkt_up_agra',
    name: 'Agra Potato & Wholesale Yard',
    district: 'Agra',
    state: 'Uttar Pradesh',
    locality: 'Agra Mandi Yard',
    type: 'apmc',
    lat: 27.1767,
    lng: 78.0081,
    address: 'Sikandra Mandi Yard, Agra, Uttar Pradesh - 282007',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T05:30:00Z',
    availableCrops: ['crop_potato', 'crop_mustard', 'crop_wheat'],
    modalPriceSummary: { crop_potato: 14.0, crop_mustard: 51.0 },
  },
  {
    id: 'mkt_lasalgaon',
    name: 'Lasalgaon APMC Market Yard (Onion Hub)',
    district: 'Nashik',
    state: 'Maharashtra',
    locality: 'Lasalgaon',
    type: 'apmc',
    lat: 20.1455,
    lng: 74.2272,
    address: 'Lasalgaon APMC, Niphad Taluka, Nashik, Maharashtra - 422306',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T06:00:00Z',
    availableCrops: ['crop_onion', 'crop_maize', 'crop_wheat'],
    modalPriceSummary: { crop_onion: 24.2, crop_maize: 19.8 },
  },
  {
    id: 'mkt_vashi',
    name: 'Vashi APMC Wholesale Market',
    district: 'Navi Mumbai',
    state: 'Maharashtra',
    locality: 'Vashi Sector 19',
    type: 'apmc',
    lat: 19.076,
    lng: 73.0076,
    address: 'Sector 19, Vashi, Navi Mumbai, Maharashtra - 400703',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T06:45:00Z',
    availableCrops: ['crop_onion', 'crop_potato', 'crop_rice', 'crop_wheat', 'crop_garlic'],
    modalPriceSummary: { crop_onion: 27.5, crop_potato: 17.2, crop_rice: 24.0 },
  },
  {
    id: 'mkt_khanna',
    name: 'Khanna Grain Market (Asia’s Largest)',
    district: 'Ludhiana',
    state: 'Punjab',
    locality: 'Khanna Grain Terminal',
    type: 'mandi',
    lat: 30.7064,
    lng: 76.2185,
    address: 'Grand Trunk Road, Khanna, Punjab - 141401',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T05:15:00Z',
    availableCrops: ['crop_wheat', 'crop_rice', 'crop_maize'],
    modalPriceSummary: { crop_wheat: 24.0, crop_rice: 22.5 },
  },
  {
    id: 'mkt_kolar',
    name: 'Kolar APMC Tomato Terminal',
    district: 'Kolar',
    state: 'Karnataka',
    locality: 'Kolar APMC Tomato Yard',
    type: 'apmc',
    lat: 13.136,
    lng: 78.129,
    address: 'NH-75 Bypass Yard, Kolar, Karnataka - 563101',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T06:00:00Z',
    availableCrops: ['crop_tomato', 'crop_green_chilli', 'crop_onion'],
    modalPriceSummary: { crop_tomato: 20.0, crop_green_chilli: 40.0 },
  },
  {
    id: 'mkt_bihar_purnia',
    name: 'Gulabbagh Mandi Purnia (Corn & Paddy)',
    district: 'Purnia',
    state: 'Bihar',
    locality: 'Gulabbagh Grain Mandi',
    type: 'mandi',
    lat: 25.78,
    lng: 87.51,
    address: 'Gulabbagh, Purnia, Bihar - 854326',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T06:00:00Z',
    availableCrops: ['crop_maize', 'crop_rice', 'crop_wheat'],
    modalPriceSummary: { crop_maize: 18.8, crop_rice: 21.0 },
  },
  {
    id: 'mkt_chennai_koyambedu',
    name: 'Koyambedu Wholesale Complex',
    district: 'Chennai',
    state: 'Tamil Nadu',
    locality: 'Koyambedu Wholesale Complex',
    type: 'apmc',
    lat: 13.069,
    lng: 80.191,
    address: 'Koyambedu, Chennai, Tamil Nadu - 600107',
    dataStatus: 'VERIFIED',
    lastUpdated: '2026-09-25T06:30:00Z',
    availableCrops: ['crop_tomato', 'crop_onion', 'crop_potato', 'crop_brinjal'],
    modalPriceSummary: { crop_tomato: 23.5, crop_onion: 28.0, crop_potato: 18.0 },
  },
];

// 4. Extended Crops with Bengali, Hindi, and English names + Realistic Baseline Values
export const EXPANDED_CROPS: Crop[] = [
  {
    id: 'crop_potato',
    name: 'Potato (Jyoti & Pukhraj)',
    hindiName: 'आलू (ज्योति व पुखराज)',
    bengaliName: 'আলু (জ্যোতি ও পোখরাজ)',
    category: 'vegetable',
    icon: '🥔',
    variety: 'Jyoti / Pukhraj',
    defaultUnit: '₹/kg',
    baseReferencePrice: 16.0,
    minPrice: 13.5,
    maxPrice: 18.5,
    modalPrice: 15.8,
    season: 'Year-round',
    description: 'Essential kitchen tuber. Sensitive to cold-storage arrival volumes and Hooghly/Burdwan yields.',
    dataStatus: 'VERIFIED',
  },
  {
    id: 'crop_onion',
    name: 'Onion (Nashik Red & White)',
    hindiName: 'प्याज (नासिक लाल व सफेद)',
    bengaliName: 'পেঁয়াজ (নাশিক লাল ও সাদা)',
    category: 'vegetable',
    icon: '🧅',
    variety: 'Nashik Red',
    defaultUnit: '₹/kg',
    baseReferencePrice: 26.0,
    minPrice: 22.0,
    maxPrice: 29.5,
    modalPrice: 26.0,
    season: 'Rabi / Late Kharif',
    description: 'Strategic kitchen commodity with heavy trading in Lasalgaon and Sealdah Koley markets.',
    dataStatus: 'VERIFIED',
  },
  {
    id: 'crop_tomato',
    name: 'Tomato (Hybrid & Desi)',
    hindiName: 'टमाटर (हाइब्रिड व देशी)',
    bengaliName: 'টমেটো (হাইব্রিড ও দেশি)',
    category: 'vegetable',
    icon: '🍅',
    variety: 'Hybrid F1',
    defaultUnit: '₹/kg',
    baseReferencePrice: 24.0,
    minPrice: 19.0,
    maxPrice: 28.0,
    modalPrice: 23.5,
    season: 'Year-round',
    description: 'Perishable crop with frequent price volatility driven by monsoon and harvest cycles.',
    dataStatus: 'VERIFIED',
  },
  {
    id: 'crop_brinjal',
    name: 'Brinjal (Eggplant / Begun)',
    hindiName: 'बैंगन (गोल व लंबा)',
    bengaliName: 'বেগুন (গোল ও লম্বা)',
    category: 'vegetable',
    icon: '🍆',
    variety: 'Muktakeshi / Green Long',
    defaultUnit: '₹/kg',
    baseReferencePrice: 28.0,
    minPrice: 22.0,
    maxPrice: 35.0,
    modalPrice: 28.0,
    season: 'Year-round',
    description: 'High daily consumption vegetable in Bengal with strong seasonal farmgate realization.',
    dataStatus: 'SAMPLE_DEMO',
  },
  {
    id: 'crop_cabbage',
    name: 'Cabbage (Green Drumhead)',
    hindiName: 'पत्तागोभी',
    bengaliName: 'বাঁধাকপি',
    category: 'vegetable',
    icon: '🥬',
    variety: 'Golden Acre',
    defaultUnit: '₹/kg',
    baseReferencePrice: 18.0,
    minPrice: 14.0,
    maxPrice: 22.0,
    modalPrice: 17.5,
    season: 'Winter / Early Summer',
    description: 'Cruciferous vegetable staple with high volume arrivals in Koley and Belur markets.',
    dataStatus: 'SAMPLE_DEMO',
  },
  {
    id: 'crop_cauliflower',
    name: 'Cauliflower (Snowball)',
    hindiName: 'फूलगोभी',
    bengaliName: 'ফুলকপি',
    category: 'vegetable',
    icon: '🥦',
    variety: 'Snowball 16',
    defaultUnit: '₹/kg',
    baseReferencePrice: 32.0,
    minPrice: 25.0,
    maxPrice: 40.0,
    modalPrice: 32.0,
    season: 'Winter',
    description: 'Popular winter vegetable with premium early-season pricing across Kolkata mandis.',
    dataStatus: 'SAMPLE_DEMO',
  },
  {
    id: 'crop_green_chilli',
    name: 'Green Chilli (G4 & Teja)',
    hindiName: 'हरी मिर्च',
    bengaliName: 'কাঁচা লঙ্কা',
    category: 'vegetable',
    icon: '🌶️',
    variety: 'G4 Hot',
    defaultUnit: '₹/kg',
    baseReferencePrice: 42.0,
    minPrice: 35.0,
    maxPrice: 52.0,
    modalPrice: 42.0,
    season: 'Year-round',
    description: 'High value spicy crop with consistent consumer and hospitality consumption.',
    dataStatus: 'VERIFIED',
  },
  {
    id: 'crop_pointed_gourd',
    name: 'Pointed Gourd (Parwal / Potal)',
    hindiName: 'परवल',
    bengaliName: 'পটল',
    category: 'vegetable',
    icon: '🥒',
    variety: 'Kalyani Swarna',
    defaultUnit: '₹/kg',
    baseReferencePrice: 38.0,
    minPrice: 30.0,
    maxPrice: 48.0,
    modalPrice: 38.0,
    season: 'Summer / Monsoon',
    description: 'Traditional Bengal delicacy grown heavily in Nadia, Hooghly, and Purba Bardhaman.',
    dataStatus: 'SAMPLE_DEMO',
  },
  {
    id: 'crop_bitter_gourd',
    name: 'Bitter Gourd (Karela / Korola)',
    hindiName: 'करेला',
    bengaliName: 'করলা / উচ্ছে',
    category: 'vegetable',
    icon: '🥒',
    variety: 'Pusa Do Mausami',
    defaultUnit: '₹/kg',
    baseReferencePrice: 34.0,
    minPrice: 28.0,
    maxPrice: 42.0,
    modalPrice: 34.0,
    season: 'Year-round',
    description: 'High medicinal and culinary demand with stable daily arrivals in wholesale yards.',
    dataStatus: 'SAMPLE_DEMO',
  },
  {
    id: 'crop_ridge_gourd',
    name: 'Ridge Gourd (Jhinga / Torai)',
    hindiName: 'तोरी / तोरई',
    bengaliName: 'ঝিঙে',
    category: 'vegetable',
    icon: '🥒',
    variety: 'Pusa Nasdar',
    defaultUnit: '₹/kg',
    baseReferencePrice: 30.0,
    minPrice: 24.0,
    maxPrice: 38.0,
    modalPrice: 30.0,
    season: 'Summer / Kharif',
    description: 'Tender cucurbit vegetable in high demand across South Bengal rural haats.',
    dataStatus: 'SAMPLE_DEMO',
  },
  {
    id: 'crop_pumpkin',
    name: 'Pumpkin (Kaddu / Kumro)',
    hindiName: 'कद्दू / कुम्हड़ा',
    bengaliName: 'মিষ্টি কুমড়ো',
    category: 'vegetable',
    icon: '🎃',
    variety: 'Baromashi Round',
    defaultUnit: '₹/kg',
    baseReferencePrice: 20.0,
    minPrice: 16.0,
    maxPrice: 25.0,
    modalPrice: 20.0,
    season: 'Year-round',
    description: 'Long shelf-life vegetable with minimal transit spoilage and steady consumption.',
    dataStatus: 'SAMPLE_DEMO',
  },
  {
    id: 'crop_garlic',
    name: 'Garlic (Desi & Ooty White)',
    hindiName: 'लहसुन',
    bengaliName: 'রসুন',
    category: 'spice',
    icon: '🧄',
    variety: 'Yamuna Safed',
    defaultUnit: '₹/kg',
    baseReferencePrice: 140.0,
    minPrice: 120.0,
    maxPrice: 165.0,
    modalPrice: 138.0,
    season: 'Rabi',
    description: 'High-value strategic spice commodity traded extensively in Posta and Mechua.',
    dataStatus: 'VERIFIED',
  },
  {
    id: 'crop_ginger',
    name: 'Ginger (Ada / Adrak)',
    hindiName: 'अदरक',
    bengaliName: 'আদা',
    category: 'spice',
    icon: '🫚',
    variety: 'Maran / Rio-de-Janeiro',
    defaultUnit: '₹/kg',
    baseReferencePrice: 80.0,
    minPrice: 65.0,
    maxPrice: 95.0,
    modalPrice: 78.0,
    season: 'Year-round',
    description: 'Cash crop with heavy arrivals from North Bengal, Assam, and Odisha into Kolkata.',
    dataStatus: 'VERIFIED',
  },
  {
    id: 'crop_wheat',
    name: 'Wheat (Sharbati & Lokwan)',
    hindiName: 'गेहूं (शरबती एवं लोकवान)',
    bengaliName: 'গম (শরবতী ও লোকওয়ান)',
    category: 'cereal',
    icon: '🌾',
    variety: 'Lokwan Grade A',
    defaultUnit: '₹/quintal',
    baseReferencePrice: 24.5,
    minPrice: 22.0,
    maxPrice: 27.0,
    modalPrice: 24.5,
    season: 'Rabi',
    description: 'High-protein grain staple. Benchmark rates tracked in Meerut, Khanna, and Posta.',
    dataStatus: 'VERIFIED',
  },
  {
    id: 'crop_rice',
    name: 'Basmati & Non-Basmati Paddy',
    hindiName: 'धान (बासमती व साधारण)',
    bengaliName: 'ধান ও চাল (মিনিকেট ও বাসমতী)',
    category: 'cereal',
    icon: '🍚',
    variety: 'Miniket / Swarna',
    defaultUnit: '₹/quintal',
    baseReferencePrice: 22.0,
    minPrice: 20.0,
    maxPrice: 25.5,
    modalPrice: 22.0,
    season: 'Kharif',
    description: 'Key dietary staple. Major production in Bardhaman, Nadia, and coastal basins.',
    dataStatus: 'VERIFIED',
  },
  {
    id: 'crop_maize',
    name: 'Maize (Corn)',
    hindiName: 'मक्का',
    bengaliName: 'ভুট্টা',
    category: 'cereal',
    icon: '🌽',
    variety: 'Yellow Hybrid',
    defaultUnit: '₹/quintal',
    baseReferencePrice: 19.5,
    minPrice: 17.5,
    maxPrice: 22.0,
    modalPrice: 19.5,
    season: 'Kharif / Rabi',
    description: 'Industrial and feed grain with heavy trading in Purnia and Lasalgaon mandis.',
    dataStatus: 'VERIFIED',
  },
  {
    id: 'crop_mustard',
    name: 'Mustard Seeds',
    hindiName: 'सरसों / राई',
    bengaliName: 'সর্ষে (হলুদ ও কালো)',
    category: 'oilseed',
    icon: '🌼',
    variety: 'Pusa Bold',
    defaultUnit: '₹/quintal',
    baseReferencePrice: 52.0,
    minPrice: 48.0,
    maxPrice: 58.0,
    modalPrice: 52.5,
    season: 'Rabi',
    description: 'Primary edible oilseed of Bengal and North India with minimum support price benchmark.',
    dataStatus: 'VERIFIED',
  },
];

// Helper: Haversine distance in km between two geo-coordinates
export function calculateHaversineDistanceKm(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 6371; // Earth radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Number((R * c).toFixed(1));
}
